### ISSUE TITLE
Update esphome2021.8.0

### ISSUE THREAD

**Issue by twty** [3ative/thermostat-project-v3#1]
Hi,
Esphome 2021.8.0, just replace the hystersis whit 4 new function ''cool_deadband, cool_overrun, heat_deadband and heat_overrun.''
I think you have to update yaml file acording to this change .
regards

**Comment by 3ative** [comment]
@twty  Thanks for the info. 👍
Please take a look at the YAML code, I updated it. Tested and working here'
Lemma know how you get on.
