### ISSUE TITLE
 thermostat-project-v3

### ISSUE THREAD

**Issue by Grzegorz484** [3ative/thermostat-project-v3#3]
Witam czy może ktoś rozwiązał problem z tym termostatem nie chce się łączyć z wifi
Ale gdy odepnę oled wszystko działa i łączy sie z HA

**Comment by 3ative** [comment]
> Hello, if someone solved the problem with this thermostat, I do not want to connect to wifi
But when I unplug it, everything works and connects to HA

If you unplug "it" how is it connecting??

**Comment by Grzegorz484** [comment]
Gdy mam podłączony wyświetlacz OLED to nie mogę połączyć się z WI FI.
Ale gdy go odepnę to działa i łączy się.

**Comment by 3ative** [comment]
> When I have an oled display connected, I cannot connect to WI FI.
But when I detach it, it works and connects.

OIC, yeah... that's been a problem since a few ESPHome updates ago. I did mention it in an 'Issue' in their GitHub but, it still hasn't been addressed. 🙄

**Comment by 3ative** [comment]
This has now been fix. So please updated to the new Yaml
