### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Pokornypetr** [3ative/thermostat-project-v3#4]
Hi, I tried your project. nice but i have a problem After drying, item L can be set after pressing the encoder button, then item H, nothing happens when the button is pressed for a longer time, nothing happens when the button is pressed again for a short time, and the contrast of the LCD cannot be set, which I would not mind, but unfortunately, the main thing is that you cannot return to item L which in my opinion is a bigger problem, how to solve it please?

**Comment by 3ative** [comment]
There's no problem with either the hardware or my code - I'm currently running same here without issue. 

- Check your setup and code - Either something is wrong or you did something wrong. 
- Also, make sure you are using the latest ESPHome update(s)

**Comment by Pokornypetr** [comment]
Hello, I have no idea why it doesn't work, I'm doing everything on a different board: https://www.aliexpress.com/item/1005003268288997.html?spm=a2g0o.order_list.order_list_main.105.2af41802uiELK1
with 2 relays but connected the same button works on changes from L to H but not back. The version of esphome is up-to-date, as well as everything, I also checked the program code, it is the same, I just changed the name of the room and removed the humidity sensor from the lcd

**Comment by 3ative** [comment]
Well if you don't know why it's not working... I don't know how you expect me to! 

If you want to pay for my flight and Hotel, I'll have a go at fixing it for you. :)

**Comment by Pokornypetr** [comment]
I was thinking of some advice on what to look for. I know that when I tried version 2 a few months ago, everything worked, but I just can't do it in this new version. do you have the code of the initial versions stored somewhere?

**Comment by Pokornypetr** [comment]
`i2c:
  frequency: 400kHz

switch:
  - platform: gpio
    id: dallas_power
    name: "Dallas Power"
    pin:
      number: GPIO03

  - platform: template
    id: heat_cool

    optimistic: true
  - platform: gpio
    id: relay_heater
    pin: D0
    inverted: true
  - platform: gpio
    id: relay_cooler
    pin: D5
    inverted: true
  - platform: template
    id: brightness
    optimistic: true

binary_sensor:
  - platform: template
    id: fire
  - platform: template
    id: cool

  - platform: gpio
    id: button
    pin:
      number: D4
      inverted: true
    on_press:
      then:
        - switch.toggle: heat_cool
    on_click:
      - min_length: 1000ms
        max_length: 20000ms
        then:
          - switch.toggle: brightness


dallas:
  - pin: D3
    update_interval: 2s

climate:
  - platform: thermostat
    min_cooling_off_time: 0s
    min_cooling_run_time: 0s
    min_heating_off_time: 0s
    min_heating_run_time: 0s
    min_idle_time: 0s
    visual:
      min_temperature: 15 °C
      max_temperature: 30 °C
    name: "${room} Thermostat"
    id: this_thermostat
    sensor: internal_temperature

### Updated for ESPHome v2022.10.0 Onwards
    default_preset: Home                      ### NEW! Use this to set Preset
    # on_boot_restore_from: memory            ### Use this to "Restore From Memeory" (A Saved State) OR...
    on_boot_restore_from: default_preset      ### Use this to set Preset to start on every Boot    
    preset:
      - name: Home
        default_target_temperature_low: $default_low
        default_target_temperature_high: $default_hi
        mode: AUTO
###########################################

    cool_action:
      - switch.turn_on: relay_cooler
      - lambda: id(cool).publish_state(true);
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: $entity_cooler

    heat_action:
      - switch.turn_on: relay_heater
      - lambda: id(fire).publish_state(true);
      - homeassistant.service:
          service: homeassistant.turn_on
          data:
            entity_id: $entity_heater

    idle_action:
      - switch.turn_off: relay_cooler
      - switch.turn_off: relay_heater
      - lambda: id(cool).publish_state(false);
      - lambda: id(fire).publish_state(false);
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: $entity_cooler
      - homeassistant.service:
          service: homeassistant.turn_off
          data:
            entity_id: $entity_heater

sensor:
  - platform: template
    id: oled_contrast

  - platform: dallas
    id: internal_temperature
    address: 0x330000035ab6a728
    filters:
    - offset: -2.0

  - platform: homeassistant
    id: internal_humidity
    entity_id: sensor.ironman_humidity

  - platform: rotary_encoder
    id: encoder
    pin_a:
      number: D6
      mode: INPUT_PULLUP
    pin_b:
      number: D7
      mode: INPUT_PULLUP
    on_clockwise:
      - if:
          condition:
            switch.is_on: brightness
          then:
            - sensor.template.publish:
                id: oled_contrast
                state: !lambda "return id(oled_contrast).state + 0.02;"
            - lambda: |-
                id(oled1).set_contrast( id(oled_contrast).state );
          else:
            - if:
                condition:
                  switch.is_on: heat_cool
                then:
                  - climate.control:
                      id: this_thermostat
                      target_temperature_high: !lambda "return id(this_thermostat).target_temperature_high + 0.5;"
                else:
                  - climate.control:
                      id: this_thermostat
                      target_temperature_low: !lambda "return id(this_thermostat).target_temperature_low + 0.5;"

    on_anticlockwise:
      then:
        - if:
            condition:
              switch.is_on: brightness
            then:
              - sensor.template.publish:
                  id: oled_contrast
                  state: !lambda "return id(oled_contrast).state - 0.02;"
              - lambda: |-
                  id(oled1).set_contrast( id(oled_contrast).state);
            else:
              - if:
                  condition:
                    switch.is_on: heat_cool
                  then:
                    - climate.control:
                        id: this_thermostat
                        target_temperature_high: !lambda "return id(this_thermostat).target_temperature_high - 0.5;"
                  else:
                    - climate.control:
                        id: this_thermostat
                        target_temperature_low: !lambda "return id(this_thermostat).target_temperature_low - 0.5;"

display:
  - platform: ssd1306_i2c
    id: oled1
    update_interval: 1.0s
    contrast: 0.4
    model: "SH1106 128x64"
    rotation: 180
    address: 0x3C
    lambda: |-
      if (id(fire).state) {id(ani_fire).next_frame(); it.image(0, 0, id(ani_fire));}
      else if (id(cool).state) {id(ani_fan).next_frame(); it.image(0, 0, id(ani_fan));}
      else {it.image(0, 0, id(home_thermometer));}

      it.print(64, 0,  id(font1), TextAlign::TOP_CENTER, "${room}");
       

      it.printf(64, 4, id(font2), TextAlign::TOP_CENTER, " %.1f°", id(internal_temperature).state);
      it.printf(1, 64, id(font3), TextAlign::BASELINE_LEFT, "L:%.1f°", id(this_thermostat).target_temperature_low);
      it.printf(127, 64, id(font3), TextAlign::BASELINE_RIGHT, "H:%.1f°", id(this_thermostat).target_temperature_high);

      if (id(brightness).state) {it.image(56, 51, id(bulb));} 
      else if (id(heat_cool).state) {it.image(56, 51, id(arrow_right));}
      else {it.image(56, 51, id(arrow_left));}

animation:
  - file: "_icons/thermostat/fan.gif"
    id: ani_fan
  - file: "_icons/thermostat/fire.gif"
    id: ani_fire
image:
  - file: "_icons/thermostat/home-thermometer.png"
    id: home_thermometer
  - file: "_icons/thermostat/arrow-left-circle-outline.png"
    id: arrow_left
  - file: "_icons/thermostat/arrow-right-circle-outline.png"
    id: arrow_right
  - file: "_icons/thermostat/lightbulb-on-outline.png"
    id: bulb
font:
  - file: "Fonts/texgyreheroscn-regular.ttf"
    id: font1
    size: 11
  - file: "Fonts/refsan.ttf"
    id: font2
    size: 42
  - file: "Fonts/refsan.ttf"
    id: font3
    size: 13
  - file: "Fonts/refsan.ttf"
    id: font4
    size: 10`

**Comment by 3ative** [comment]
I can't debug your code if it's not formatted properly - what you've shared there is not YAML.

The code hasn't changed for over 10 months, and even that was a small change to the "DALLAS Sensor Log".
 - So it can't be that.
 
 Things to look for:
 - Check your code
 - Check your components
 - Check your wiring
 
 I hope you can appreciate there's not much I can do from here, as I can't see what you've done or how you've done it. Obviously the project works. So again, you've either done something different or used something different.

**Comment by Pokornypetr** [comment]
Svůjkod jsem poslal I also have the same connection with HW. I have no doubt that everything works for you jenne, I can find out why it doesn't work for me :D. as I said the first time I press the button on the encoder the setting status changes from L to H the arrow turns on the lcd and I can set the H value when I press the encoder button again nothing happens. Nothing happens when the button is pressed for a long time.

**Comment by 3ative** [comment]
> Svůjkod jsem poslal 

No, you sent text. I can't help if it's not YAML (original) formatted.

> I also have the same connection with HW. 

Maybe... but you're not using the same D1 Mini and you haven't told me what other HW you've changed too.

> as I said the first time I press the button on the encoder the setting status changes from L to H the arrow turns on the lcd and I can set the H value when I press the encoder button again nothing happens. Nothing happens when the button is pressed for a long time.

As I said, "Check your components", maybe your button is faulty?
