### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Pokornypetr** [3ative/thermostat-project-v3#5]
hello, as I indicated in the previous problem, switching between L and H with the button and setting the backlight did not work for me, everything was solved by writing **Input_pullaup** :`- platform: gpio
    id: button
    pin:
      number: D4
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      then:
        - switch.toggle: heat_cool`

**Comment by 3ative** [comment]
I guess it was a hardware issue then.
Cool you found it, there's no way I could have from here.
